/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.EmptyBorder;
//
//

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Pierre
 */
public class Chat_Item extends javax.swing.JLayeredPane {
    private JLabel label;
    
   
    Font myFont;
   

    /**
     * Creates new form Chat_Item
     */
    public Chat_Item() {
        initComponents();
        
        try{
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        myFont = Font.createFont(Font.TRUETYPE_FONT, new File("C:\\Users\\Pierre\\Downloads\\sofiapro\\Fonts\\sofiapro-light.otf")).deriveFont(16f);
        
        ge.registerFont(myFont);
        }catch(FontFormatException | IOException e){
            e.printStackTrace();
        }
        
        txt.setEditable(false);
        txt.setBackground(new Color(0,0,0,0));
        txt.setOpaque(false);
      
    }
    public void setText(String text){
        txt.setText(text);
        txt.setForeground(new Color(0));
        txt.setFont(myFont);
        
    }
    
    public void setTime(String time){
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.RIGHT, 0,0));
        layer.setBorder(new EmptyBorder(0,5,10,5));
        label = new JLabel(time);
        
        label.setForeground(new Color(110,110,110));
        label.setHorizontalTextPosition(JLabel.LEFT);
        layer.add(label);
        add(layer);
    }
    
    public void sendSuccess(){
        if(label != null){
            label.setIcon(new ImageIcon(getClass().getResource("/javaapplication1/images/tick.png")));
        }
    }
    
     public void seen(){
        if(label != null){
            label.setIcon(new ImageIcon(getClass().getResource("/javaapplication1/images/double_tick.png")));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javaapplication1.JIMSendTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 10));
        add(txt);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2 = (Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0,0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication1.JIMSendTextPane txt;
    // End of variables declaration//GEN-END:variables
}
