/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import javax.swing.JButton;

import net.miginfocom.swing.MigLayout;
/**
 *
 * @author Pierre
 */
public class Chat_Body extends javax.swing.JPanel {

    /**
     * Creates new form Chat_Body
     */
    public Chat_Body() {
        initComponents();
        init();
        addItemLeft("Jopay, kamusta ka na?");
        addItemLeft("Palagi kitang pinapanood, nakikita");
        addItemLeft("Jopay, pasensiya ka na");
        addItemLeft("Wala rin kasi akong makausap at kasama");
        addItemRight("'Wag ka nang mawala ('wag ka nang mawala)\n" +
                    "'Wag ka nang mawala ('wag ka nang mawala)\n" +
                    "Ngayon");

        addItemLeft("Dadalhin kita sa aming bahay\n" +
                    "'Di tayo mag-aaway\n" +
                    "Aalis tayo sa tunay na mundo");
        
        addItemRight("Dadalhin kita sa aming bahay");
        addItemRight("'Di tayo mag-aaway");
        addItemRight("Aalis tayo sa tunay na mundo");
        
    }
    
     private void init(){
        body.setLayout(new MigLayout("fillx", "", "15[]15"));
        body.setBackground(new Color(237,240,246));
        sp.setVerticalScrollBar(new ScrollBar());
        sp.getVerticalScrollBar().setBackground(Color.white);
        
    } 
     public void addItemRight(String text){
         Chat_Right item = new Chat_Right();
         item.setText(text);
         body.add(item, "wrap, al right, w ::80%");
         //body.add(new JButton("what if"), "wrap, al right, w ::80%");
         if(text.contains("name")){
             addItemLeft("hi my name is Jopay");
         }
         body.repaint();
         body.revalidate();
     }
     public void addItemLeft(String text){
         Chat_Left item = new Chat_Left();
         item.setText(text);
         body.add(item, "wrap, w ::80%");
         body.repaint();
         body.revalidate();
     }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();

        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        sp.setViewportView(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
